{% set version = '0.1.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggforce
  version: {{ version|replace("-", "_") }}

source:
  fn: ggforce_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggforce_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggforce/ggforce_{{ version }}.tar.gz
  sha256: c4ea83a674793836eac876f8cfdf363ea677d9a947b4461226883a6d7cedcd73

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
  host:
    - r-base
    - r-mass
    - r-rcpp >=0.12.2
    - r-dplyr
    - r-ggplot2 >=2.2.0
    - r-gtable
    - r-lazyeval
    - r-scales
    - r-tweenr >=0.1.5
    - r-units >=0.4
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-rcpp >=0.12.2
    - r-dplyr
    - r-ggplot2 >=2.2.0
    - r-gtable
    - r-lazyeval
    - r-scales
    - r-tweenr >=0.1.5
    - r-units >=0.4

test:
  commands:
    - $R -e "library('ggforce')"           # [not win]
    - "\"%R%\" -e \"library('ggforce')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ggforce
  license: GPL (>= 2)
  summary: The aim of 'ggplot2' is to aid in visual data investigations. This focus has led to
    a lack of facilities for composing specialised plots. 'ggforce' aims to be a collection
    of mainly new stats and geoms that fills this gap. All additional functionality
    is aimed to come through the official extension system so using 'ggforce' should
    be a stable experience.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
